### ISSUE TITLE
Stream drops out quickly after channel switch

### ISSUE THREAD

**Issue by rangeles** [kodi-pvr/pvr.vdr.vnsi#85]
Versions:
kodi 16.1
vdr 2.2.0
vnsiserver 1.3.1
pvr.vdr.vnsi 1.11.15

After a kodi upgrade from 15.2 to 16.1, I've been trying to figure out why vnsi has been unable to tune into channels. I'll preface this by stating that vnsiserver was able to work with kodi 15.2 + pvr.vdr.vnsi 1.10.10. And since my vnsiserver hasn't changed, I am certain there is some regression in the addon.

On the vnsiserver side, I did notice this error:
`Jul 09 10:20:31 fillmore vdr[6188]: [6245] VNSI-Error: cxSocket::read: read() error at 0/4`

I debugged it further and found that the ::read() call in cxSocket::read() was returning with ECONNRESET errno. Not sure why, I am thinking probably a premature connection close on the addon side?

On the kodi side, I did notice this:
`10:20:31 T:140256753989376   ERROR: AddOnLog: VDR VNSI Client: DemuxRead - std::exception`

Tracing that out hasn't been fun. Still trying to see if I can get a stack trace on that exception.

I've attached debug logs alongside this. Any tips for further tracking down the issue?
[vdr.log.txt](https://github.com/kodi-pvr/pvr.vdr.vnsi/files/355666/vdr.log.txt)
[kodi.log.txt](https://github.com/kodi-pvr/pvr.vdr.vnsi/files/355665/kodi.log.txt)

Lastly, I wanted to say thanks for maintaining this addon. It is greatly appreciated.

**Comment by FernetMenta** [comment]
who created this build? I remember some issues I fixed in platform which was renamed to p8-platform. maybe this build does not include those.

**Comment by rangeles** [comment]
Currently, I am running this on Gentoo Linux. While the p8-platform was indeed renamed, I still have the older (libplatform) package installed. The platform package is just built from git but from the "oldname" branch. Are you suggesting that there are fixes in the master branch that need to be backported? Do you happen to know which commits?

**Comment by rangeles** [comment]
So, I was able to track the issue down, and it looks to me like it should be patched in the server instead. You can find my fix [here](https://github.com/FernetMenta/vdr-plugin-vnsiserver/pull/68).

**Comment by FernetMenta** [comment]
nice, thanks!
